AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an Application Load Balancer to be used with the Express Example App
Parameters:
  VPCID:
    Type: 'AWS::EC2::VPC::Id'
    Description: Choose the VPCId of your existing VPC
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: >-
      Associate at least 2 SubnetIds existing in your VPC with the Load balancer
Resources:
  ALBSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPCID
      GroupDescription: Inbound HTTP
      SecurityGroupIngress: 
        - Description: 'Allow HTTP IPv4 IN'
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
  ALBTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Name: !Sub '${AWS::StackName}-TG'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCID
      Tags:
        - Key: CloudformationStackName
          Value: !Ref 'AWS::StackName'
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref 'AWS::StackName'
              - TargetGroup
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref  ALBTargetGroup
      LoadBalancerArn: !Ref ALBv2
      Port: 80
      Protocol: HTTP
  ALBv2:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Subnets: !Ref Subnets
      Name: !Sub '${AWS::StackName}-ALB'
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref 'AWS::StackName'
              - ELBv2
      SecurityGroups: 
        - !Ref ALBSG

Outputs:
  ALBDNS:
    Description: DNS Name of the LoadBalancer
    Value: !GetAtt ALBv2.DNSName
    Export:
      Name: ALBv2-dnsname
  TGARN:
    Description: DNS Name of the LoadBalancer
    Value: !Ref ALBTargetGroup
    Export:
      Name: !Sub '${AWS::StackName}-ALBTG-ARN'